# SwiftLint configuration for swift-json-feed-standard
# Inherits from the shared parent configuration in swift-standards

parent_config: https://raw.githubusercontent.com/swift-standards/swift-standards/main/.swiftlint.yml

# Package-specific overrides (if needed)
# Add any swift-json-feed-standard specific rules here
